#!/bin/bash

# golang programming environment installer
# Copyright (C) 2014-2016  geosoft1@gmail.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

GITSERVER="github.com"
GOPATH=$HOME/go-programs
if [ -z $1 ]; then
   echo "Usage: clone githubusername/projectname"
   exit
fi
git clone git@$GITSERVER:$1.git $GOPATH/src/$GITSERVER/$1
echo "Done."
