#!/bin/bash

# golang programming environment installer
# Copyright (C) 2014-2016  geosoft1@gmail.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

usage()  {
   echo "Usage: "`basename "$0"`" [options]"
   echo "Options:"
   echo "present   present tool"
   echo "delve     delve debugger"
   exit
}

if [ -z $1 ]; then
   usage   exit
fi

case $1 in
   present ) repo=golang.org/x/tools/cmd/present;;
   delve   ) repo=github.com/derekparker/delve/cmd/dlv;;
   #
   # feel free to add new commands here :-)
   #
   *       ) usage;;
esac

echo "Installing $1 ($repo)..."
go get $repo

echo "Done."
