#!/bin/bash
GITUSER=`awk 'NR==2 {print $3}' $HOME/.gitconfig`
REPO=${PWD##*/}
echo -n "Create repository github.com/$GITUSER/$REPO [y/n]"
read opt
if [ "$opt" == "n" ]; then
   exit
fi
echo -n "Enter your github.com/$GITUSER password:"
read PASSWORD
err=`curl -s -u $GITUSER:$PASSWORD https://api.github.com/user/repos -d '{"name":"'$REPO'"}' | awk '/message/ { gsub(/^[\t]+|[\",]/,"");print }'`
if [ "$err" != "" ]; then
   echo -n $err
   echo 
   exit
fi
git init
git add *
git commit -m "first commit"
git remote add origin git@github.com:$GITUSER/$REPO.git
git push -u origin master
echo "Done."

