#!/usr/bin/env bash

# cloud tool
# Copyright (C) 2014-2016  geosoft1@gmail.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Project path structure
#
# /home/username/src/github.com/githubusername/projectname/*.go
# |HOME         |BASEPATH                     |BASENAME   |.servers
# |REMOTE_HOME  |                             |PROJECT_NAME
#                                             |EXECUTABLE_NAME
#
# .servers file structure
#
# REMOTE_ADDR REMOTE_PORT REMOTE_USER
#

LONG_NAME="Cloud tool"
CODE_NAME="Quantum Teleporter"
AUTHOR="geosoft1@gmail.com"
COPYRIGHT="Copyright (C) 2014-2016  $AUTHOR"
MAJOR_VERSION=1
MINOR_VERSION=2
PATCH_VERSION=0
STAGE="alpha"
VERSION=$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION
ROOT=`dirname $0`
NAME=`basename $0`
DATE="05 July 2016"
LAST="19 December 2016"

GOROOT=$HOME/go
GOBIN=$GOROOT/bin

SERVERS_FILE=$PWD/.servers
TMP_FOLDER=/tmp/.ssh

SSH_OPTIONS=(-o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" -q)

BASENAME=`basename $PWD`
PROJECT_NAME=$BASENAME
EXECUTABLE_NAME=$PROJECT_NAME
BASEPATH=`echo $PWD | sed -e "s,$HOME\/,," | sed -e "s,\/$BASENAME$,,"`

set -e

usage()  {
   echo "Usage: $NAME [options]"
   echo "Options:"
   echo "init              -- push ssh key to remote server(s)"
   echo "push              -- push curent source+binary tree"
   #echo "pull             -- pull remote source+binary tree"
   echo "run [filename]    -- run project or file remote,view result locally"
   echo "detach [filename] -- run and detach project or file remote"
   echo "teleport          -- push and run project remote,view result locally"
   echo "kill              -- stop the project remote"
   #echo "build            -- build project remote from remote source"
   echo "deploy            -- deploy project on remote server(s)"
   echo "remove            -- uninstall project from remote server(s)"
   echo "terminal          free remote ssh commands"
   echo "version           version"
   exit
}

[ -z $1 ] && usage

#read server list from .servers file (ip port user)
if [ ! -f $SERVERS_FILE ]; then
   echo -n "Remote server ";read REMOTE_ADDR
   #try to guess remote ssh port
   echo -n "Remote port [ENTER for 22] ";read REMOTE_PORT
   if [ -z "$REMOTE_PORT" ]; then REMOTE_PORT="22"; fi
   #try to guess remote user
   echo -n "Remote user [ENTER for $USER] ";read REMOTE_USER
   [ -z $REMOTE_USER ] && REMOTE_USER=$USER
   echo -e "$REMOTE_ADDR $REMOTE_PORT $REMOTE_USER" > $SERVERS_FILE
fi

eval $(cat .servers | awk '{print "REMOTE_ADDR=\""$1"\";REMOTE_PORT=\""$2"\";REMOTE_USER=\""$3"\""}')

getRemoteEnv() {
   REMOTE_HOME=`ssh -p $REMOTE_PORT "${SSH_OPTIONS[@]}" $REMOTE_USER@$REMOTE_ADDR printenv HOME`
   PROJECT_PATH=$REMOTE_HOME/$BASEPATH/$PROJECT_NAME
}

init() {
   echo "-- push ssh key to $REMOTE_USER@$REMOTE_ADDR:$REMOTE_PORT"
   if [ ! -f $HOME/.ssh/id_rsa.pub ]; then
     echo "No public key found." && exit
   fi
   #scp create destination folder only if it copies folders
   #so we prepare here a temporary folder for key transfer
   mkdir -p $TMP_FOLDER
   #copy only the key in temporary folder
   cp $HOME/.ssh/id_rsa.pub $TMP_FOLDER/authorized_keys
   #safe deploy the public key to remote server
   if [ -z $LITEIDE_TERM ]; then
      scp -P $REMOTE_PORT -r "${SSH_OPTIONS[@]}" $TMP_FOLDER $REMOTE_USER@$REMOTE_ADDR:
   else
      echo -n "Password "
      $GOBIN/tools/ssh_askpass scp -P $REMOTE_PORT -r "${SSH_OPTIONS[@]}" $TMP_FOLDER $REMOTE_USER@$REMOTE_ADDR:
   fi
   #clean the mess
   rm -rf $TMP_FOLDER

   #if [ -z $LITEIDE_TERM ]; then
   #   ssh-copy-id -o "StrictHostKeyChecking no" -f $REMOTE_USER@$REMOTE_ADDR
   #else
   #   echo -n "Password "
      # StrictHostKeyChecking no
      # -f force overite the key
   #   $GOBIN/tools/ssh_askpass ssh-copy-id -o "StrictHostKeyChecking no" -f $REMOTE_USER@$REMOTE_ADDR
   #fi
}

push() {
   echo "-- push current source+binary tree on $REMOTE_USER@$REMOTE_ADDR:$REMOTE_PORT"
   #force copy read-only files like some .git content
   ssh -p $REMOTE_PORT "${SSH_OPTIONS[@]}" $REMOTE_USER@$REMOTE_ADDR mkdir -p $BASEPATH
   ssh -p $REMOTE_PORT "${SSH_OPTIONS[@]}" $REMOTE_USER@$REMOTE_ADDR chmod -R +w $BASEPATH
   scp -P $REMOTE_PORT -r "${SSH_OPTIONS[@]}" $PWD $REMOTE_USER@$REMOTE_ADDR:$BASEPATH
}

run() {
   echo "-- run project on $REMOTE_USER@$REMOTE_ADDR:$REMOTE_PORT"
   [ $1 ] && EXECUTABLE_NAME=$1
   getRemoteEnv
   ssh -p $REMOTE_PORT "${SSH_OPTIONS[@]}" $REMOTE_USER@$REMOTE_ADDR $PROJECT_PATH/$EXECUTABLE_NAME
}

detach() {
   echo "-- run and detach project on $REMOTE_USER@$REMOTE_ADDR:$REMOTE_PORT"
   [ $1 ] && EXECUTABLE_NAME=$1
   getRemoteEnv
   ssh -p $REMOTE_PORT "${SSH_OPTIONS[@]}" $REMOTE_USER@$REMOTE_ADDR "sh -c 'nohup $PROJECT_PATH/$EXECUTABLE_NAME > /dev/null 2>&1 &'"
}

teleport() {
   echo "-- teleporting project"
   push && run
}

_kill() {
   echo "-- kill project on $REMOTE_USER@$REMOTE_ADDR:$REMOTE_PORT"
   [ $1 ] && EXECUTABLE_NAME=$1
   ssh -p $REMOTE_PORT "${SSH_OPTIONS[@]}" $REMOTE_USER@$REMOTE_ADDR killall $EXECUTABLE_NAME
}

deploy() {
   echo "-- deploy project on $REMOTE_USER@$REMOTE_ADDR:$REMOTE_PORT"
   getRemoteEnv
   ssh -p $REMOTE_PORT "${SSH_OPTIONS[@]}" $REMOTE_USER@$REMOTE_ADDR "(crontab -l 2>/dev/null; echo '@reboot $PROJECT_PATH/$EXECUTABLE_NAME') | crontab -"
}

remove() {
   echo "-- remove project from $REMOTE_USER@$REMOTE_ADDR:$REMOTE_PORT"
   getRemoteEnv
   ssh -p $REMOTE_PORT "${SSH_OPTIONS[@]}" $REMOTE_USER@$REMOTE_ADDR "(crontab -l 2>/dev/null; echo '@reboot $PROJECT_PATH/$EXECUTABLE_NAME') | grep -v $EXECUTABLE_NAME | crontab -"
   ssh -p $REMOTE_PORT "${SSH_OPTIONS[@]}" $REMOTE_USER@$REMOTE_ADDR rm -rf $PROJECT_PATH
}

terminal() {
   ssh -p $REMOTE_PORT "${SSH_OPTIONS[@]}" $REMOTE_USER@$REMOTE_ADDR
}

case $1 in
   init    ) init;;
   push    ) push;;
   run     ) run $2;;
   detach  ) detach $2;;
   teleport) teleport;;
   kill    ) _kill $2;;
   deploy  ) _kill || true
             remove
             push && deploy
             detach;;
   remove  ) _kill || true
             remove;;
   terminal) terminal;;
   version ) echo $VERSION && exit;;
   *       ) usage;;
esac

echo "Done."
