#!/usr/bin/env bash

# github tool
# Copyright (C) 2014-2019  geosoft1@gmail.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

LONG_NAME="Github tool"
CODE_NAME=""
AUTHOR="geosoft1@gmail.com"
COPYRIGHT="Copyright (C) 2014-2019  $AUTHOR"
VERSION=1.1.1
STAGE="release"
ROOT=`dirname $0`
NAME=`basename $0`

GITSERVER=github.com
GITUSER=`awk 'NR==2 {print $3}' $HOME/.gitconfig`

BASENAME=`basename $PWD`
PROJECT_NAME=$BASENAME

GOPATH=$HOME

usage()  {
   echo "Usage: $NAME [options]"
   echo "Options:"
   echo "new                        make a new github repository from current folder"
   echo "clone githubuser/project   clone a github project in GOPATH/src/github.com/USER"
   echo "version                    version"
   exit
}

new () {
   echo -n "Create repository $GITSERVER/$GITUSER/$PROJECT_NAME [y/n] " && read option
   [ $option == y ] || exit

   echo -n "Password:" && read PASSWORD
   curl -s -u $GITUSER:$PASSWORD https://api.$GITSERVER/user/repos -d '{"name":"'$PROJECT_NAME'"}' | awk '/message/ { gsub(/^[\t]+|[\",]/,"");print }' || exit

   git init
   git add *
   git commit -m "first commit"
   git remote add origin git@$GITSERVER:$GITUSER/$PROJECT_NAME.git
   git push -u origin master
}

clone () {
   git clone git@$GITSERVER:$1.git $GOPATH/src/$GITSERVER/$1
}

case $1 in
   new     ) new;;
   clone   ) clone $2;;
   version ) echo $VERSION && exit;;
   *       ) usage;;
esac

echo "Done."
