#!/usr/bin/env bash

# install tool
# Copyright (C) 2014-2016  geosoft1@gmail.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

LONG_NAME="Install tool"
CODE_NAME=""
AUTHOR="geosoft1@gmail.com"
COPYRIGHT="Copyright (C) 2014-2016  $AUTHOR"
MAJOR_VERSION=1
MINOR_VERSION=1
PATCH_VERSION=0
STAGE="release"
VERSION=$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION
DATE=""
LAST="06 August 2016"

usage()  {
   echo "Usage: "`basename "$0"`" [options]"
   echo "Options:"
   echo "present   present tool"
   echo "delve     delve debugger"
   echo "version   version"
   exit
}

case $1 in
   present ) URL=golang.org/x/tools/cmd/present;;
   delve   ) URL=github.com/derekparker/delve/cmd/dlv;;
   version ) echo $VERSION && exit;;
   *       ) usage;;
esac

echo "Installing $1 (from $URL)..." && go get $URL

echo "Done."
