#!/bin/bash

# golang programming environment installer
# Copyright (C) 2014-2016  geosoft1@gmail.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

GITSERVER=github.com
GITUSER=`awk 'NR==2 {print $3}' $HOME/.gitconfig`
REPO=`basename $PWD`

echo -n "Create repository $GITSERVER/$GITUSER/$REPO [y/n] " && read option
[ $option == y ] || exit

echo -n "Password:" && read PASSWORD
curl -s -u $GITUSER:$PASSWORD https://api.$GITSERVER/user/repos -d '{"name":"'$REPO'"}' | awk '/message/ { gsub(/^[\t]+|[\",]/,"");print }' || exit

git init
git add *
git commit -m "first commit"
git remote add origin git@$GITSERVER:$GITUSER/$REPO.git
git push -u origin master

echo "Done."
